"""initial schema

Revision ID: f23693425fae
Revises: 
Create Date: 2026-04-24 11:53:41.314220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f23693425fae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('player_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name_ja', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('hometown', sa.String(length=100), nullable=True),
    sa.Column('school', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index(op.f('ix_players_birth_date'), 'players', ['birth_date'], unique=False)
    op.create_index(op.f('ix_players_nationality'), 'players', ['nationality'], unique=False)
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name_ja', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=8), nullable=True),
    sa.Column('arena', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('official_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_index(op.f('ix_teams_code'), 'teams', ['code'], unique=False)
    op.create_table('games',
    sa.Column('schedule_key', sa.String(length=12), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('competition', sa.String(length=80), nullable=True),
    sa.Column('section', sa.String(length=40), nullable=True),
    sa.Column('is_cs', sa.Boolean(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=True),
    sa.Column('tipoff', sa.String(length=10), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('home_team_id <> away_team_id', name='ck_games_distinct_teams'),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.team_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.team_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('schedule_key')
    )
    op.create_index(op.f('ix_games_away_team_id'), 'games', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_games_competition'), 'games', ['competition'], unique=False)
    op.create_index(op.f('ix_games_game_date'), 'games', ['game_date'], unique=False)
    op.create_index(op.f('ix_games_home_team_id'), 'games', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_games_is_cs'), 'games', ['is_cs'], unique=False)
    op.create_index(op.f('ix_games_is_final'), 'games', ['is_final'], unique=False)
    op.create_index(op.f('ix_games_season'), 'games', ['season'], unique=False)
    op.create_table('player_team_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('positions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', name='uq_player_team_history_ps')
    )
    op.create_index(op.f('ix_player_team_history_player_id'), 'player_team_history', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_team_history_season'), 'player_team_history', ['season'], unique=False)
    op.create_index(op.f('ix_player_team_history_team_id'), 'player_team_history', ['team_id'], unique=False)
    op.create_table('roster_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('game_type', sa.String(length=20), nullable=False),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('ppg', sa.Float(), nullable=True),
    sa.Column('fg_pct', sa.Float(), nullable=True),
    sa.Column('three_fg_pct', sa.Float(), nullable=True),
    sa.Column('ft_pct', sa.Float(), nullable=True),
    sa.Column('rpg', sa.Float(), nullable=True),
    sa.Column('apg', sa.Float(), nullable=True),
    sa.Column('topg', sa.Float(), nullable=True),
    sa.Column('spg', sa.Float(), nullable=True),
    sa.Column('bpg', sa.Float(), nullable=True),
    sa.Column('eff', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', 'game_type', name='uq_roster_season_stats')
    )
    op.create_index(op.f('ix_roster_season_stats_game_type'), 'roster_season_stats', ['game_type'], unique=False)
    op.create_index(op.f('ix_roster_season_stats_player_id'), 'roster_season_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_roster_season_stats_season'), 'roster_season_stats', ['season'], unique=False)
    op.create_index(op.f('ix_roster_season_stats_team_id'), 'roster_season_stats', ['team_id'], unique=False)
    op.create_table('team_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('game_type', sa.String(length=20), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('ppg', sa.Float(), nullable=True),
    sa.Column('opp_ppg', sa.Float(), nullable=True),
    sa.Column('fg_pct', sa.Float(), nullable=True),
    sa.Column('three_fg_pct', sa.Float(), nullable=True),
    sa.Column('ft_pct', sa.Float(), nullable=True),
    sa.Column('rpg', sa.Float(), nullable=True),
    sa.Column('apg', sa.Float(), nullable=True),
    sa.Column('topg', sa.Float(), nullable=True),
    sa.Column('spg', sa.Float(), nullable=True),
    sa.Column('bpg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'season', 'game_type', name='uq_team_season_stats')
    )
    op.create_index(op.f('ix_team_season_stats_game_type'), 'team_season_stats', ['game_type'], unique=False)
    op.create_index(op.f('ix_team_season_stats_season'), 'team_season_stats', ['season'], unique=False)
    op.create_index(op.f('ix_team_season_stats_team_id'), 'team_season_stats', ['team_id'], unique=False)
    op.create_table('player_box_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_key', sa.String(length=12), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('is_starter', sa.Boolean(), nullable=False),
    sa.Column('min_played_sec', sa.Integer(), nullable=True),
    sa.Column('pts', sa.Integer(), nullable=True),
    sa.Column('fga', sa.Integer(), nullable=True),
    sa.Column('fgm', sa.Integer(), nullable=True),
    sa.Column('tpa', sa.Integer(), nullable=True),
    sa.Column('tpm', sa.Integer(), nullable=True),
    sa.Column('fta', sa.Integer(), nullable=True),
    sa.Column('ftm', sa.Integer(), nullable=True),
    sa.Column('oreb', sa.Integer(), nullable=True),
    sa.Column('dreb', sa.Integer(), nullable=True),
    sa.Column('ast', sa.Integer(), nullable=True),
    sa.Column('tov', sa.Integer(), nullable=True),
    sa.Column('stl', sa.Integer(), nullable=True),
    sa.Column('blk', sa.Integer(), nullable=True),
    sa.Column('pf', sa.Integer(), nullable=True),
    sa.Column('plus_minus', sa.Integer(), nullable=True),
    sa.Column('eff', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_key'], ['games.schedule_key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_key', 'player_id', name='uq_player_box_scores')
    )
    op.create_index(op.f('ix_player_box_scores_player_id'), 'player_box_scores', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_box_scores_schedule_key'), 'player_box_scores', ['schedule_key'], unique=False)
    op.create_index(op.f('ix_player_box_scores_team_id'), 'player_box_scores', ['team_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_key', sa.String(length=12), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('home_win_prob', sa.Float(), nullable=False),
    sa.Column('away_win_prob', sa.Float(), nullable=False),
    sa.Column('predicted_margin', sa.Float(), nullable=True),
    sa.Column('actual_home_win', sa.Boolean(), nullable=True),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('away_win_prob >= 0 AND away_win_prob <= 1', name='ck_predictions_away_prob_range'),
    sa.CheckConstraint('home_win_prob >= 0 AND home_win_prob <= 1', name='ck_predictions_home_prob_range'),
    sa.ForeignKeyConstraint(['schedule_key'], ['games.schedule_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_key', 'model_version', 'predicted_at', name='uq_predictions')
    )
    op.create_index(op.f('ix_predictions_model_version'), 'predictions', ['model_version'], unique=False)
    op.create_index(op.f('ix_predictions_predicted_at'), 'predictions', ['predicted_at'], unique=False)
    op.create_index(op.f('ix_predictions_schedule_key'), 'predictions', ['schedule_key'], unique=False)
    op.create_table('team_box_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_key', sa.String(length=12), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('pts', sa.Integer(), nullable=True),
    sa.Column('fga', sa.Integer(), nullable=True),
    sa.Column('fgm', sa.Integer(), nullable=True),
    sa.Column('fg_pct', sa.Float(), nullable=True),
    sa.Column('tpa', sa.Integer(), nullable=True),
    sa.Column('tpm', sa.Integer(), nullable=True),
    sa.Column('tp_pct', sa.Float(), nullable=True),
    sa.Column('fta', sa.Integer(), nullable=True),
    sa.Column('ftm', sa.Integer(), nullable=True),
    sa.Column('ft_pct', sa.Float(), nullable=True),
    sa.Column('oreb', sa.Integer(), nullable=True),
    sa.Column('dreb', sa.Integer(), nullable=True),
    sa.Column('reb', sa.Integer(), nullable=True),
    sa.Column('ast', sa.Integer(), nullable=True),
    sa.Column('tov', sa.Integer(), nullable=True),
    sa.Column('stl', sa.Integer(), nullable=True),
    sa.Column('blk', sa.Integer(), nullable=True),
    sa.Column('pf', sa.Integer(), nullable=True),
    sa.Column('q1', sa.Integer(), nullable=True),
    sa.Column('q2', sa.Integer(), nullable=True),
    sa.Column('q3', sa.Integer(), nullable=True),
    sa.Column('q4', sa.Integer(), nullable=True),
    sa.Column('ot', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['schedule_key'], ['games.schedule_key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_key', 'team_id', name='uq_team_box_scores')
    )
    op.create_index(op.f('ix_team_box_scores_schedule_key'), 'team_box_scores', ['schedule_key'], unique=False)
    op.create_index(op.f('ix_team_box_scores_team_id'), 'team_box_scores', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_box_scores_team_id'), table_name='team_box_scores')
    op.drop_index(op.f('ix_team_box_scores_schedule_key'), table_name='team_box_scores')
    op.drop_table('team_box_scores')
    op.drop_index(op.f('ix_predictions_schedule_key'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_predicted_at'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_model_version'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_player_box_scores_team_id'), table_name='player_box_scores')
    op.drop_index(op.f('ix_player_box_scores_schedule_key'), table_name='player_box_scores')
    op.drop_index(op.f('ix_player_box_scores_player_id'), table_name='player_box_scores')
    op.drop_table('player_box_scores')
    op.drop_index(op.f('ix_team_season_stats_team_id'), table_name='team_season_stats')
    op.drop_index(op.f('ix_team_season_stats_season'), table_name='team_season_stats')
    op.drop_index(op.f('ix_team_season_stats_game_type'), table_name='team_season_stats')
    op.drop_table('team_season_stats')
    op.drop_index(op.f('ix_roster_season_stats_team_id'), table_name='roster_season_stats')
    op.drop_index(op.f('ix_roster_season_stats_season'), table_name='roster_season_stats')
    op.drop_index(op.f('ix_roster_season_stats_player_id'), table_name='roster_season_stats')
    op.drop_index(op.f('ix_roster_season_stats_game_type'), table_name='roster_season_stats')
    op.drop_table('roster_season_stats')
    op.drop_index(op.f('ix_player_team_history_team_id'), table_name='player_team_history')
    op.drop_index(op.f('ix_player_team_history_season'), table_name='player_team_history')
    op.drop_index(op.f('ix_player_team_history_player_id'), table_name='player_team_history')
    op.drop_table('player_team_history')
    op.drop_index(op.f('ix_games_season'), table_name='games')
    op.drop_index(op.f('ix_games_is_final'), table_name='games')
    op.drop_index(op.f('ix_games_is_cs'), table_name='games')
    op.drop_index(op.f('ix_games_home_team_id'), table_name='games')
    op.drop_index(op.f('ix_games_game_date'), table_name='games')
    op.drop_index(op.f('ix_games_competition'), table_name='games')
    op.drop_index(op.f('ix_games_away_team_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_teams_code'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_players_nationality'), table_name='players')
    op.drop_index(op.f('ix_players_birth_date'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
